version: 2.1

jobs:
  lint-dockerfile:
    docker:
      - image: hadolint/hadolint:latest
    steps:
      - checkout
      - run:
          name: Lint Dockerfile
          command: hadolint ./karsajobs/Dockerfile

  test-app:
    docker:
      - image: golang:1.17
    steps:
      - checkout
      - run:
          name: Run Unit Tests
          command: go test -v -short --count=1 $(go list ./...)

  build-app-karsajobs:
    docker:
      - image: docker:latest
    steps:
      - checkout
      - run:
          name: Build and Push Docker Image
          command: |
            go build -o karsajobs
            docker build -t ghcr.io/wahyurin/a433-microservices/karsajobs:latest .
            echo "$TOKEN" | docker login ghcr.io -u "WahyuriN" --password-stdin
            docker push ghcr.io/wahyurin/a433-microservices/karsajobs:latest

workflows:
  version: 2
  karsajobs:
    jobs:
      - lint-dockerfile
      - test-app:
          requires:
            - lint-dockerfile
      - build-app-karsajobs:
          requires:
            - test-app
