version: 2.1

jobs:
  lint-dockerfile:
    docker:
      - image: hadolint/hadolint:latest
    steps:
      - checkout
      - run: hadolint Dockerfile

  build-app-karsajobs-ui:
    docker:
      - image: golang:1.17
    steps:
      - checkout
      - run:
          name: Build karsajobs-ui
          command: |
            go build -o karsajobs-ui
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build and Push Docker Image
          command: |
            docker build -t ghcr.io/wahyurin/a433-microservices/karsajobs-ui:latest .
            echo "$DOCKER_PASSWORD" | docker login ghcr.io -u "$DOCKER_USERNAME" --password-stdin
            docker push ghcr.io/wahyurin/a433-microservices/karsajobs-ui:latest

workflows:
  version: 2
  karsajobs-ui-ci:
    jobs:
      - lint-dockerfile
      - build-app-karsajobs-ui:
          requires:
            - lint-dockerfile
